### ISSUE TITLE
Kotlin 1.4 compatibility

### ISSUE THREAD

**Issue by gerbit** [nsk90/kstatemachine#61]
0.18.0 -> 0.20.0 steped to kotlin 1.5, 0.18.0 was useful to me with 1.4 kotlin.
Still I was able to port 0.21.0 to 1.4 (tests are passing), and just want to clarify the further plans of the project. I assume, some 1.4 bugs and limits going to slow down project development and support.

**Comment by nsk90** [comment]
That is just a result that I update Kotlin version to 1.8 in this library.. kotlin 1.4 is deprecated..

did version 0.18.0 worked for you? I am asking because I have an app where I checked compatibility and I had a problems with 1.4 and 1.5 versions (before 0.20.0 update) and now I see the same with 1.5 & 1.6 kotlin for 0.20.0+

**Comment by nsk90** [comment]
any activity?

**Comment by gerbit** [comment]
Yep, ported 0.21 to 1.4, it works fine on my setup (AOSP 12)
