### ISSUE TITLE
exportToPlantUml throws "JobCancellationException: ScopeCoroutine has completed normally;"

### ISSUE THREAD

**Issue by gepz** [nsk90/kstatemachine#66]
```
    @OptIn(ExperimentalCoroutinesApi::class)
    @Test
    fun testUML() = runTest {
        val test = makeUML() // throws "JobCancellationException: ScopeCoroutine has completed normally;"
        assert(test != "")
    }

    suspend fun makeUML() = coroutineScope {
        val m = makeM()
        val uml = m.exportToPlantUml()
        return@coroutineScope uml
    }

    suspend fun makeM() = coroutineScope {
        return@coroutineScope createStateMachine(this) {
            setInitialState(state {  })
        }
    }
```

The above JUnit5 test testUML will throw JobCancellationException for some reason.
It wouldn't if I put `val uml = m.exportToPlantUml()` inside makeM though.
I'm corrently using the legacy non-coroutine method as the workaround

**Comment by nsk90** [comment]
I think it because scope created here `suspend fun makeM() = coroutineScope {` and used in state machine here `createStateMachine(this)` is already cancelled when you call `m.exportToPlantUml()`.

Check this version, please.

**Comment by gepz** [comment]
Does the scope used by the factory function have to exist throughout the entire life time of the state machine?
If so, how can I save the machine as a variable?

**Comment by nsk90** [comment]
Yes life time of a scope should be equal or longer then machine lifetime. There is no problem with storing machine as variable. Just create your couroutine scope or use standard one (like GlobalScope). The reason of your problem is that you are using `coroutineScope` function which is not designed for scope creation, but for parallel decomposition of work.
https://kt.academy/article/cc-constructing-scope here you can find samples of scope creation that I mean.

**Comment by gepz** [comment]
I see, thanks for the info.
